# Конфигурация вашего сервера
HTTP_SERVER:
  HTTP_HOST: your host
  HTTP_PORT: your port
# Информация о пользователе "отправителя", с его почты сервис будет отправлять письма клиентам.
# В графе "SENDER_PASSWORD" нужно указать пароль для приложений, его можно найти на сайте почты, которую вы хотите привязать к сервису,
# также нужно указать порт и хост почтового сервиса отправителя SMTP_HOST и SMTP_PORT, вы без проблем найдете эту информацию в интернете.
# Затем, укажите количество повторных попыток при отправке и базовое время ожидания, между попытками (если не знаете что выбрать оставьте
# поля пустыми, они примут значения по умолчанию: 3 и 5 соответственно).
SMTP:
#  Информация об почте отправителя
  SENDER_EMAIL: your@mail.ru
  SENDER_PASSWORD: passwordForApplicationsFromYourMail
#  Информация об SMTP (пример для mail.ru)
  SMTP_HOST: smtp.mail.ru
  SMTP_PORT: 587
  SKIP_VERIFY: false/true
  MAX_RETRIES: 3
  BASIC_RETRY_PAUSE: 5
#  В разработке
REDIS:
  REDIS_ADDR:
  REDIS_PASSWORD:
  REDIS_DB:
  REDIS_USERNAME:
# Выберите какого вида будет логгер в вашем сервисе: dev = development, prod = production,
# в production логгере используется классический zap.NewProduction
LOGGER:
  env: dev/prod