name: Run Go Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run tests and generate coverage
        run: |
          go test -covermode=atomic -coverprofile=coverage.out -v ./...
          go tool cover -func=coverage.out > coverage.txt

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-go@v2
        with:
          coverage_file: coverage.out

      - name: Move badge to public folder
        run: |
          mkdir -p coverage-badge
          mv coverage.svg coverage-badge/

      - name: Deploy badge to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage-badge
          publish_branch: gh-pages
